"Resource/UI/TeamMenu.res"
{
	"team"
	{
		"ControlName"	"CTeamMenu"
		"fieldName"		"team"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"f0"
		"tall"			"480"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
	}
	
	"SysMenu"
	{
		"ControlName"	"Menu"
		"fieldName"		"SysMenu"
		"xpos"			"0"
		"ypos"			"999999"
		"wide"			"0"
		"tall"			"0"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"tabPosition"	"0"
	}

	"mapname"
	{
		"ControlName"	"Label"
		"fieldName"		"mapname"
		"xpos"			"r100"
		"ypos"			"c200"
		"wide"			"200"
		"tall"			"60"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"1"
		"font"		"MontserratBlack12"
		"fgcolor"				"255 255 255 150"
	}
	
    "JoinBlueButton"
	{
		"ControlName"	"CExButton"
		"fieldName"		"JoinBlueButton"
        "textinsetx"	"5"
        "textinsetY"	"0"
		"use_proportional_insets" "1"
		"xpos"			"c-140"		
		"ypos"			"c-10"		
		"zpos"			"6"
		"wide"			"118"
		"tall"			"22"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"BLU"
		"textAlignment"	"west"
		"Command"		"jointeam blue"
		"border_default"	""
		"border_armed"		""
		"paintbackground"	"0"
		"font"			"MontserratBlack32"
		"defaultFgColor_override" "White"
		"armedFgColor_override" "PFGreen"
	}
	
	"BlueTeamBG"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"BlueTeamBG"
		"xpos"			"40"
		"ypos"			"10"
		"zpos"			"1"
		"wide"			"170"
		"tall"			"40"
		"visible"		"1"
		"enabled"		"1"
		"bgcolor_override"	"PFBluTeamTransparent"
		"PaintBackgroundType"	"0"
		
		"pin_to_sibling" 			"JoinBlueButton"
	}
	
	"BlueCount"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"BlueCount"
		"xpos"			"-50"
		"ypos"			"5"
		"zpos"			"2"
		"wide"			"90"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%bluecount%"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"1"
		"font"			"MontserratBlack32"
		"fgcolor"		"White"
		
		"pin_to_sibling" 			"JoinBlueButton"
	}	
	
	"BluePlayersIcon"
	{
		"ControlName"	"ImagePanel"		
		"fieldName"		"BluePlayersIcon"
		"xpos"			"-55"
		"ypos"			"-4"
		"zpos"			"3"
		"wide"			"12"
		"tall"			"22"
		"visible"		"1"
		"enabled"		"1"
		"image"			"capture_icon"
		"scaleImage"	"1"
		
		"pin_to_sibling" 			"BlueCount"
	}
	
	"BlueTeamImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"BlueTeamImage"
		"xpos"			"80"
		"ypos"			"32"
		"zpos"			"2"
		"wide"			"80"
		"tall"			"80"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../passtime/hud/passtime_teamlogo_blue.vtf"
		"scaleImage"		"1"
		"proportionaltoparent"	"1"
		
		"pin_to_sibling"			"JoinBlueButton"
		"pin_corner_to_sibling"		"PIN_BOTTOM_LEFT"
		"pin_to_sibling_corner"		"PIN_TOP_LEFT"
	}
	
	"JoinRedButton"
	{
		"ControlName"	"CExButton"
		"fieldName"		"JoinRedButton"
        "textinsetx"	"5"
        "textinsetY"	"0"
		"use_proportional_insets" "1"
		"xpos"			"c20"		
		"ypos"			"c-10"		
		"zpos"			"6"
		"wide"			"118"
		"tall"			"22"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"RED"
		"textAlignment"	"east"
		"Command"		"jointeam Red"
		"border_default"	""
		"border_armed"		""
		"paintbackground"	"0"
		"font"			"MontserratBlack32"
		"defaultFgColor_override" "White"
		"armedFgColor_override" "PFGreen"
	}
	
	"RedTeamBG"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"RedTeamBG"
		"xpos"			"10"
		"ypos"			"10"
		"zpos"			"1"
		"wide"			"170"
		"tall"			"40"
		"visible"		"1"
		"enabled"		"1"
		"bgcolor_override"	"PFRedTeamTransparent"
		"PaintBackgroundType"	"0"
		
		"pin_to_sibling" 			"JoinRedButton"
	}
	
	"RedCount"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"RedCount"
		"xpos"			"20"
		"ypos"			"5"
		"zpos"			"2"
		"wide"			"90"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%redcount%"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"1"
		"font"			"MontserratBlack32"
		"fgcolor"		"White"
		
		"pin_to_sibling" 			"JoinRedButton"
	}	
	
	"RedPlayersIcon"
	{
		"ControlName"	"ImagePanel"		
		"fieldName"		"RedPlayersIcon"
		"xpos"			"-20"
		"ypos"			"-4"
		"zpos"			"3"
		"wide"			"12"
		"tall"			"22"
		"visible"		"1"
		"enabled"		"1"
		"image"			"capture_icon"
		"scaleImage"	"1"
		
		"pin_to_sibling" 			"RedCount"
	}
	
	"RedTeamImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"RedTeamImage"
		"xpos"			"-120"
		"ypos"			"32"
		"zpos"			"2"
		"wide"			"80"
		"tall"			"80"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../passtime/hud/passtime_teamlogo_red.vtf"
		"scaleImage"		"1"
		"proportionaltoparent"	"1"
		
		"pin_to_sibling"			"JoinRedButton"
		"pin_corner_to_sibling"		"PIN_BOTTOM_LEFT"
		"pin_to_sibling_corner"		"PIN_TOP_LEFT"
	}
	
	
    "JoinSpectatorsButton"
	{
		"ControlName"	"CExButton"
		"fieldName"		"JoinSpectatorsButton"
        "textinsetx"	"5"
        "textinsetY"	"0"
		"use_proportional_insets" "1"
		"xpos"			"c-60"		
		"ypos"			"c50"		
		"zpos"			"6"
		"wide"			"118"
		"tall"			"22"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"Spectate"
		"textAlignment"	"center"
		"Command"		"jointeam spectator"
		"border_default"	""
		"border_armed"		""
		"paintbackground"	"0"
		"font"			"MontserratBlack24"
		"defaultFgColor_override" "White"
		"armedFgColor_override" "PFGreen"
	}
	
	"SpectatorsTeamBG"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"RedTeamBG"
		"xpos"			"10"
		"ypos"			"10"
		"zpos"			"1"
		"wide"			"140"
		"tall"			"40"
		"visible"		"1"
		"enabled"		"1"
		"bgcolor_override"	"PFGrey"
		"PaintBackgroundType"	"0"
		
		"pin_to_sibling" 			"JoinSpectatorsButton"
	}
	
	"CancelButton"
	{
		"ControlName"	"CExButton"
		"fieldName"		"CancelButton"
		"xpos"			"c-75"
		"ypos"			"r80"
		"zpos"			"6"
		"wide"			"150"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_Cancel"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"border_default"	""
		"border_armed"		""
		"paintbackground"	"0"
		"command"		"cancelmenu"
		"font"			"MontserratBlack24"
		"defaultFgColor_override" "White"
		"armedFgColor_override" "PFGreen"
	}