"Resource/UI/TrainingComplete.res"
{
 	"TrainingComplete"
	{
		"ControlName"		"CTFTrainingComplete"
		"fieldName"			"TrainingComplete"
		"xpos"				"0"
		"ypos"				"0"
		"zpos"				"0"
		"wide"				"f0"
		"tall"				"480"
		"visible"			"1"
		"enabled"			"1"
  
		"Next" [$WIN32] 
		{
			"ControlName"		"CExButton"
			"fieldName"		"Next"
			"xpos"			"r190"
			"xpos_lodef"			"r222"
			"xpos_hidef"			"r232"
			"ypos"			"r40"
			"ypos_lodef"			"r64"
			"ypos_hidef"			"r54"
			"zpos"			"6"
			"wide"			"150"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"2"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"		"0"
			"labelText"		"#Button_NextTraining"
			"textAlignment"		"center"
			"dulltext"		"0"
			"brighttext"		"0"
			"wrap"		"0"
			"command"		"next"
			"font"			"MontserratBlack22"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
		}

		"Quit" [$WIN32] 
		{
			"ControlName"		"CExButton"
			"fieldName"		"Quit"
			"xpos"			"r190"
			"xpos_lodef"			"r222"
			"xpos_hidef"			"r232"
			"ypos"			"r40"
			"ypos_lodef"			"r64"
			"ypos_hidef"			"r54"
			"zpos"			"6"
			"wide"			"150"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"2"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"		"0"
			"labelText"		"#Button_QuitTraining"
			"textAlignment"		"center"
			"dulltext"		"0"
			"brighttext"		"0"
			"wrap"		"0"
			"command"		"quit"
			"font"			"MontserratBlack22"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
		}	
		
		"Replay" [$WIN32] 
		{
			"ControlName"	"CExButton"
			"fieldName"		"Replay"
			"xpos"			"40"
			"xpos_hidef"			"50"
			"ypos"			"r40"
			"ypos_lodef"			"r64"
			"ypos_hidef"			"r54"
			"zpos"			"6"
			"wide"			"150"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"2"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		"#Button_ReplayTraining"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"command"		"replay"
			"font"			"MontserratBlack22"
			"fgcolor"		"Black"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
		}
		
		"BottomBar"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"BottomBar"
			"xpos"			"0"
			"ypos"			"r50"
			"ypos_lodef"			"r74"
			"ypos_hidef"			"r65"
			"zpos"			"5"
			"wide"			"f0"
			"tall"			"50"
			"tall_lodef"			"74"
			"tall_hidef"			"65"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"	
			"fillcolor"		"32 32 32 255"
			"PaintBackgroundType"	"0"
		}	

		"TopBar"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"TopBar"
			"xpos"			"0"
			"ypos"			"0"
			"ypos_lodef"			"r74"
			"ypos_hidef"			"r65"
			"zpos"			"5"
			"wide"			"f0"
			"tall"			"50"
			"tall_lodef"			"74"
			"tall_hidef"			"65"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"	
			"fillcolor"		"32 32 32 255"
			"PaintBackgroundType"	"0"
		}
	}

	"JackHappy" //:JACKHAPPY:
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"JackHappy"
		"xpos"			"c-32"
		"ypos"			"167"
		"zpos"			"2"
		"wide"			"64"
		"tall"			"64"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../hud/jackhappy"
		"scaleImage"	"1"
	}

	"Results"
	{
		"ControlName"	"EditablePanel"
		"fieldName"	"Results"
		"xpos"		"c-200"
		"ypos"		"105"
		"zpos"		"1"
		"wide"		"400"
		"tall"		"480"
		"visible"	"1"
		"enabled"	"1"

		"ResultsLabel"
		{
			"ControlName"		"Label"
			"fieldName"		"ResultsLabel"
		  	"font"			"MontserratBlack32"
			"labelText"		"%wintext%"
			"textAlignment"		"center"
			"xpos"			"0"
			"ypos"			"10"
			"zpos"			"1"
			"wide"			"400"
			"tall"			"20"
			"autoResize"		"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor_override"		"White"
		}
		"ResultsBG"
		{
			"ControlName"	"EditablePanel"
			"fieldName"		"ResultsBG"
			"xpos"			"0"
			"ypos"			"0"
			"wide"			"400"
			"tall"			"275"
			"visible"		"1"
			"PaintBackgroundType"	"2"
			"border"		"TFFatLineBorderOpaque"
		}
		"ResultsText"
		{
			"ControlName"		"CExRichText"
			"fieldName"		"ResultsText"
			"xpos"			"15"
			"ypos"			"150"
			"zpos"			"2"
			"wide"			"370"
			"tall"			"215"
			"autoResize"		"3"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"		"0"
			"maxchars"		"-1"
			"text"			""
			"wrap"			"1"
			"textAlignment"		"north-west"
			"font"			"MontserratLight16"
		}
	}			
}

