// This file was generated by devtools/genbuildinfo.py .
// Do ***not*** edit it by hand.

const char* g_szbuildInfo = "p4ss cd2e39e6 (modified) at 2026-02-05T22:39:03 (Linux 6.18.7-arch1-1)";
const char* g_szbuildCommit = "cd2e39e6 (modified)";
const char* g_szbuildDate = "2026-02-05T22:39:03";
const char* g_szbuildOs = "Linux 6.18.7-arch1-1";

