block()
include(cmake/source_lib_base.cmake)

add_library(vgui_controls STATIC)

set_target_properties(vgui_controls PROPERTIES PREFIX "")
target_include_directories(vgui_controls PRIVATE
${SRCDIR}/thirdparty
${SRCDIR}/thirdparty/cef
${SRCDIR}/vgui2/vgui_controls
)

set(SOURCE_LIST
${SRCDIR}/vgui2/vgui_controls/AnalogBar.cpp
${SRCDIR}/vgui2/vgui_controls/AnimatingImagePanel.cpp
${SRCDIR}/vgui2/vgui_controls/AnimationController.cpp
${SRCDIR}/vgui2/vgui_controls/BitmapImagePanel.cpp
${SRCDIR}/vgui2/vgui_controls/BuildFactoryHelper.cpp
${SRCDIR}/vgui2/vgui_controls/BuildGroup.cpp
${SRCDIR}/vgui2/vgui_controls/BuildModeDialog.cpp
${SRCDIR}/vgui2/vgui_controls/Button.cpp
${SRCDIR}/vgui2/vgui_controls/CheckButton.cpp
${SRCDIR}/vgui2/vgui_controls/CheckButtonList.cpp
${SRCDIR}/vgui2/vgui_controls/CircularProgressBar.cpp
${SRCDIR}/vgui2/vgui_controls/ComboBox.cpp
${SRCDIR}/vgui2/vgui_controls/consoledialog.cpp
${SRCDIR}/vgui2/vgui_controls/ControllerMap.cpp
${SRCDIR}/vgui2/vgui_controls/controls.cpp
${SRCDIR}/vgui2/vgui_controls/cvartogglecheckbutton.cpp
${SRCDIR}/vgui2/vgui_controls/DirectorySelectDialog.cpp
${SRCDIR}/vgui2/vgui_controls/Divider.cpp
${SRCDIR}/vgui2/vgui_controls/EditablePanel.cpp
${SRCDIR}/vgui2/vgui_controls/ExpandButton.cpp
${SRCDIR}/vgui2/vgui_controls/FileOpenDialog.cpp
${SRCDIR}/vgui2/vgui_controls/FileOpenStateMachine.cpp
${SRCDIR}/public/filesystem_helpers.cpp
${SRCDIR}/vgui2/vgui_controls/FocusNavGroup.cpp
${SRCDIR}/vgui2/vgui_controls/Frame.cpp
${SRCDIR}/vgui2/vgui_controls/GraphPanel.cpp
${SRCDIR}/vgui2/vgui_controls/HTML.cpp
${SRCDIR}/vgui2/vgui_controls/Image.cpp
${SRCDIR}/vgui2/vgui_controls/ImageList.cpp
${SRCDIR}/vgui2/vgui_controls/ImagePanel.cpp
${SRCDIR}/vgui2/vgui_controls/InputDialog.cpp
${SRCDIR}/vgui2/vgui_controls/KeyBindingHelpDialog.cpp
${SRCDIR}/vgui2/vgui_controls/KeyBoardEditorDialog.cpp
${SRCDIR}/vgui2/vgui_controls/KeyRepeat.cpp
${SRCDIR}/vgui2/vgui_controls/Label.cpp
${SRCDIR}/vgui2/vgui_controls/ListPanel.cpp
${SRCDIR}/vgui2/vgui_controls/ListViewPanel.cpp
${SRCDIR}/vgui2/vgui_controls/Menu.cpp
${SRCDIR}/vgui2/vgui_controls/MenuBar.cpp
${SRCDIR}/vgui2/vgui_controls/MenuButton.cpp
${SRCDIR}/vgui2/vgui_controls/MenuItem.cpp
${SRCDIR}/vgui2/vgui_controls/MessageBox.cpp
${SRCDIR}/vgui2/vgui_controls/MessageDialog.cpp
${SRCDIR}/vgui2/vgui_controls/Panel.cpp
${SRCDIR}/vgui2/vgui_controls/PanelListPanel.cpp
${SRCDIR}/vgui2/vgui_controls/PerforceFileExplorer.cpp
${SRCDIR}/vgui2/vgui_controls/PerforceFileList.cpp
${SRCDIR}/vgui2/vgui_controls/perforcefilelistframe.cpp
${SRCDIR}/vgui2/vgui_controls/ProgressBar.cpp
${SRCDIR}/vgui2/vgui_controls/ProgressBox.cpp
${SRCDIR}/vgui2/vgui_controls/PropertyDialog.cpp
${SRCDIR}/vgui2/vgui_controls/PropertyPage.cpp
${SRCDIR}/vgui2/vgui_controls/PropertySheet.cpp
${SRCDIR}/vgui2/vgui_controls/QueryBox.cpp
${SRCDIR}/vgui2/vgui_controls/RadioButton.cpp
${SRCDIR}/vgui2/vgui_controls/RichText.cpp
${SRCDIR}/vgui2/vgui_controls/RotatingProgressBar.cpp
${SRCDIR}/vgui2/vgui_controls/savedocumentquery.cpp
${SRCDIR}/vgui2/vgui_controls/ScalableImagePanel.cpp
${SRCDIR}/vgui2/vgui_controls/ScrollableEditablePanel.cpp
${SRCDIR}/vgui2/vgui_controls/ScrollBar.cpp
${SRCDIR}/vgui2/vgui_controls/ScrollBarSlider.cpp
${SRCDIR}/vgui2/vgui_controls/SectionedListPanel.cpp
${SRCDIR}/vgui2/vgui_controls/Slider.cpp
${SRCDIR}/vgui2/vgui_controls/Splitter.cpp
${SRCDIR}/vgui2/vgui_controls/subrectimage.cpp
${SRCDIR}/vgui2/vgui_controls/TextEntry.cpp
${SRCDIR}/vgui2/vgui_controls/TextImage.cpp
${SRCDIR}/vgui2/vgui_controls/ToggleButton.cpp
${SRCDIR}/vgui2/vgui_controls/Tooltip.cpp
${SRCDIR}/vgui2/vgui_controls/ToolWindow.cpp
${SRCDIR}/vgui2/vgui_controls/TreeView.cpp
${SRCDIR}/vgui2/vgui_controls/TreeViewListControl.cpp
${SRCDIR}/vgui2/vgui_controls/URLLabel.cpp
${SRCDIR}/vgui2/vgui_controls/WizardPanel.cpp
${SRCDIR}/vgui2/vgui_controls/WizardSubPanel.cpp
${SRCDIR}/vgui2/src/vgui_key_translation.cpp
)
set(HEADER_LIST
${SRCDIR}/public/vgui_controls/AnalogBar.h
${SRCDIR}/public/vgui_controls/AnimatingImagePanel.h
${SRCDIR}/public/vgui_controls/AnimationController.h
${SRCDIR}/public/vgui_controls/BitmapImagePanel.h
${SRCDIR}/public/vgui_controls/BuildGroup.h
${SRCDIR}/public/vgui_controls/BuildModeDialog.h
${SRCDIR}/public/vgui_controls/Button.h
${SRCDIR}/public/vgui_controls/CheckButton.h
${SRCDIR}/public/vgui_controls/CheckButtonList.h
${SRCDIR}/public/vgui_controls/CircularProgressBar.h
${SRCDIR}/public/Color.h
${SRCDIR}/public/vgui_controls/ComboBox.h
${SRCDIR}/public/vgui_controls/consoledialog.h
${SRCDIR}/public/vgui_controls/ControllerMap.h
${SRCDIR}/public/vgui_controls/Controls.h
${SRCDIR}/public/vgui_controls/cvartogglecheckbutton.h
${SRCDIR}/public/vgui_controls/DialogManager.h
${SRCDIR}/public/vgui_controls/DirectorySelectDialog.h
${SRCDIR}/public/vgui_controls/Divider.h
${SRCDIR}/public/vgui_controls/EditablePanel.h
${SRCDIR}/public/vgui_controls/ExpandButton.h
${SRCDIR}/public/vgui_controls/FileOpenDialog.h
${SRCDIR}/public/vgui_controls/FileOpenStateMachine.h
${SRCDIR}/public/filesystem.h
${SRCDIR}/public/filesystem_helpers.h
${SRCDIR}/public/vgui_controls/FocusNavGroup.h
${SRCDIR}/public/vgui_controls/Frame.h
${SRCDIR}/public/vgui_controls/GraphPanel.h
${SRCDIR}/public/vgui_controls/HTML.h
${SRCDIR}/public/vgui_controls/Image.h
${SRCDIR}/public/vgui_controls/ImageList.h
${SRCDIR}/public/vgui_controls/ImagePanel.h
${SRCDIR}/public/vgui_controls/InputDialog.h
${SRCDIR}/public/tier1/interface.h
${SRCDIR}/public/vgui_controls/KeyBindingHelpDialog.h
${SRCDIR}/public/vgui_controls/KeyBindingMap.h
${SRCDIR}/public/vgui_controls/KeyBoardEditorDialog.h
${SRCDIR}/public/vgui_controls/KeyRepeat.h
${SRCDIR}/public/tier1/KeyValues.h
${SRCDIR}/public/vgui_controls/Label.h
${SRCDIR}/public/vgui_controls/ListPanel.h
${SRCDIR}/public/vgui_controls/ListViewPanel.h
${SRCDIR}/public/tier0/memdbgoff.h
${SRCDIR}/public/tier0/memdbgon.h
${SRCDIR}/public/tier1/mempool.h
${SRCDIR}/public/vgui_controls/Menu.h
${SRCDIR}/public/vgui_controls/MenuBar.h
${SRCDIR}/public/vgui_controls/MenuButton.h
${SRCDIR}/public/vgui_controls/MenuItem.h
${SRCDIR}/public/vgui_controls/MessageBox.h
${SRCDIR}/public/vgui_controls/MessageDialog.h
${SRCDIR}/public/vgui_controls/MessageMap.h
${SRCDIR}/public/vgui_controls/Panel.h
${SRCDIR}/public/vgui_controls/PanelAnimationVar.h
${SRCDIR}/public/vgui_controls/PanelListPanel.h
${SRCDIR}/public/vgui_controls/PerforceFileExplorer.h
${SRCDIR}/public/vgui_controls/PerforceFileList.h
${SRCDIR}/public/vgui_controls/perforcefilelistframe.h
${SRCDIR}/public/vgui_controls/PHandle.h
${SRCDIR}/public/vgui_controls/ProgressBar.h
${SRCDIR}/public/vgui_controls/ProgressBox.h
${SRCDIR}/public/vgui_controls/PropertyDialog.h
${SRCDIR}/public/vgui_controls/PropertyPage.h
${SRCDIR}/public/vgui_controls/PropertySheet.h
${SRCDIR}/public/vgui_controls/QueryBox.h
${SRCDIR}/public/vgui_controls/RadioButton.h
${SRCDIR}/public/vgui_controls/RichText.h
${SRCDIR}/public/vgui_controls/RotatingProgressBar.h
${SRCDIR}/public/vgui_controls/savedocumentquery.h
${SRCDIR}/public/vgui_controls/ScalableImagePanel.h
${SRCDIR}/public/vgui_controls/ScrollableEditablePanel.h
${SRCDIR}/public/vgui_controls/ScrollBar.h
${SRCDIR}/public/vgui_controls/ScrollBarSlider.h
${SRCDIR}/public/vgui_controls/SectionedListPanel.h
${SRCDIR}/public/vgui_controls/Slider.h
${SRCDIR}/public/vgui_controls/Splitter.h
${SRCDIR}/public/vgui_controls/subrectimage.h
${SRCDIR}/public/vgui_controls/TextEntry.h
${SRCDIR}/public/vgui_controls/TextImage.h
${SRCDIR}/public/vgui_controls/ToggleButton.h
${SRCDIR}/public/vgui_controls/Tooltip.h
${SRCDIR}/public/vgui_controls/ToolWindow.h
${SRCDIR}/public/vgui_controls/TreeView.h
${SRCDIR}/public/vgui_controls/TreeViewListControl.h
${SRCDIR}/public/vgui_controls/URLLabel.h
${SRCDIR}/public/tier1/utlmemory.h
${SRCDIR}/public/tier1/utlrbtree.h
${SRCDIR}/public/tier1/utlvector.h
${SRCDIR}/public/vgui_controls/WizardPanel.h
${SRCDIR}/public/vgui_controls/WizardSubPanel.h
)

target_sources(vgui_controls PRIVATE ${SOURCE_LIST})
source_group("C++ Source" FILES ${SOURCE_LIST})

target_sources(vgui_controls PRIVATE ${HEADER_LIST})
source_group("Public Header Files" FILES ${HEADER_LIST})
endblock()

